# src/trusted_data_agent/agent/response_models.py
from pydantic import BaseModel, Field
from typing import List, Optional

class KeyMetric(BaseModel):
    """
    Represents a single, primary metric that can summarize the answer
    to a user's query, such as a total count or a status.
    """
    value: str = Field(..., description="The value of the metric, represented as a string.")
    label: str = Field(..., description="A short, descriptive label for the metric.")

class Observation(BaseModel):
    """
    Represents a single textual insight, finding, or piece of contextual
    information related to the final answer.
    """
    text: str = Field(..., description="The content of the observation as a natural language string.")

class Synthesis(BaseModel):
    """
    Represents a single, distilled summary or finding generated by an
    intermediate TDA_LLMTask phase during a complex workflow. This captures
    the agent's step-by-step analytical conclusions.
    """
    text: str = Field(..., description="The content of the synthesized finding as a natural language string.")

class CanonicalResponse(BaseModel):
    """
    The standardized, structured data model for a final summary from the LLM.
    This model serves as the contract between the data generation tier (Tier 1)
    and the presentation/rendering tier (Tier 2), ensuring a reliable and
    decoupled architecture.
    """
    direct_answer: str = Field(
        ...,
        description="A direct and concise sentence that factually answers the user's primary question."
    )
    key_metric: Optional[KeyMetric] = Field(
        None,
        description="The optional, single primary metric summarizing the response."
    )
    key_observations: List[Observation] = Field(
        default_factory=list,
        description="A list of supporting details, findings, and contextual insights."
    )
    synthesis: List[Synthesis] = Field(
        default_factory=list,
        description="A list of distilled summaries from intermediate analytical steps (TDA_LLMTask results)."
    )

class ReportSection(BaseModel):
    """Represents a single named section within a complex report."""
    title: str = Field(..., description="The title of this report section.")
    content: str = Field(..., description="The markdown-formatted content of this section.")

class PromptReportResponse(BaseModel):
    """
    The standardized, structured data model for a final report generated
    from a complex, prompt-driven workflow.
    """
    title: str = Field(..., description="The main title of the report, often reflecting the name of the executed prompt.")
    executive_summary: str = Field(..., description="A high-level summary of the findings.")
    report_sections: List[ReportSection] = Field(
        default_factory=list,
        description="A list of detailed sections that make up the body of the report."
    )
