#!/usr/bin/env python3
"""
Deletes orphan RAG case studies that don't have associated sessions.
Reads the orphan_cases.json file generated by identify_orphan_cases.py and deletes the files.
"""

import json
from pathlib import Path
import sys

# Add parent directory to path to import from src
sys.path.insert(0, str(Path(__file__).parent.parent))
from src.trusted_data_agent.agent.rag_template_generator import RAGTemplateGenerator

def delete_orphan_cases(orphan_file):
    """Delete orphan case files."""
    
    if not orphan_file.exists():
        print(f"Error: Orphan cases file not found: {orphan_file}")
        print("Please run identify_orphan_cases.py first to generate the orphan list.")
        sys.exit(1)
    
    # Load orphan cases
    with open(orphan_file, 'r', encoding='utf-8') as f:
        orphan_cases = json.load(f)
    
    # Safety check: Filter out preserved session IDs
    PRESERVED_SESSION_IDS = {
        RAGTemplateGenerator.TEMPLATE_SESSION_ID,  # Template-generated cases
    }
    
    filtered_cases = []
    preserved_count = 0
    for case in orphan_cases:
        if case.get('session_id') in PRESERVED_SESSION_IDS:
            preserved_count += 1
            print(f"⚠ Skipping preserved case: {case.get('case_id')} (session_id: {case.get('session_id')})")
        else:
            filtered_cases.append(case)
    
    orphan_cases = filtered_cases
    
    if preserved_count > 0:
        print(f"\n✓ Protected {preserved_count} template-generated cases from deletion\n")
    
    if not orphan_cases:
        print("No orphan cases to delete (after filtering preserved cases).")
        return
    
    print("=" * 80)
    print("ORPHAN CASE DELETION")
    print("=" * 80)
    print()
    print(f"Found {len(orphan_cases)} orphan cases to delete.")
    print()
    
    # Confirm deletion
    response = input("Are you sure you want to delete these cases? (yes/no): ").strip().lower()
    if response not in ['yes', 'y']:
        print("Deletion cancelled.")
        return
    
    print()
    print("Deleting orphan cases...")
    print("-" * 80)
    
    deleted_count = 0
    failed_count = 0
    
    for case in orphan_cases:
        file_path = Path(case['file_path'])
        
        try:
            if file_path.exists():
                file_path.unlink()
                deleted_count += 1
                print(f"✓ Deleted: {file_path.name}")
            else:
                print(f"⚠ Already gone: {file_path.name}")
                deleted_count += 1  # Count as deleted since it's not there
        except Exception as e:
            failed_count += 1
            print(f"✗ Failed to delete {file_path.name}: {e}")
    
    print()
    print("=" * 80)
    print("DELETION SUMMARY")
    print("=" * 80)
    print(f"Successfully deleted: {deleted_count}")
    print(f"Failed: {failed_count}")
    print(f"Total processed: {len(orphan_cases)}")
    print()
    
    if failed_count == 0:
        print("✓ All orphan cases have been deleted successfully!")
        # Clean up the orphan cases file
        orphan_file.unlink()
        print(f"✓ Removed {orphan_file.name}")
    else:
        print(f"⚠ {failed_count} cases could not be deleted. Please check errors above.")
    
    print()

if __name__ == "__main__":
    # Set up paths
    project_root = Path(__file__).resolve().parents[1]
    orphan_file = project_root / "maintenance" / "orphan_cases.json"
    
    # Run deletion
    delete_orphan_cases(orphan_file)
